version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: Laptop House-app:dev
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - MONGODB_URI=mongodb://mongo:27017/Laptop House
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
